// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    Board: typeof import('./src/components/Board.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    DrawerNavigation: typeof import('./src/components/DrawerNavigation.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
